### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by axl411** [eleme/mobilists#18]
After pulling from remote, I `git submodule update`, then `npm install`, and `make start`, got the following error:

```
➜  Mobilests git:(master) make start
module.js:457
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ChaoGu/Programming/projects/XCode/WorkRelated/Eleme/misc/Mobilests/editor/index.js:1:79)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
make: *** [start] Error 1
```

**Comment by axl411** [comment]
I deleted the project and cloned again, worked.
